from sqlalchemy.orm import sessionmaker
from o2m_modul import Game, Race, Class, Profession, engine

session = sessionmaker(bind=engine)()

dh = Class(name="Demon Hunter", party_role="DPS or Tank", resources="Health and Fury", armor_type="Leather", weapon="Warglaves, Fist Weapons, One-handed Axes, Swords")
monk = Class(name="Monk", party_role="Tank, Heal, DPS", resources="Health, Chi, Energy, Mana", armor_type="Leather", weapon="Fist weapon, One-handed Axes, Maces, Swords, Polearms, Staves")
shaman = Class(name="Shaman", party_role="DPS or Heal", resources="Health, Mana, Maelstorm", armor_type="Mail", weapon="Daggers, Fist Weapons, Axes, Maces, Shield, Staves")
warlock = Class(name="Warlock", party_role="DPS", resources="Health, Mana, Soul shards", armor_type="Cloth", weapon="Daggers, One-handed Swords, Wands, Staves")
rogue = Class(name="Rogue", party_role="DPS", resources="Health, Energy, Combo points", armor_type="Leather", weapon="Daggers, Fist Weapons, One-handed Axes, Maces, Swords")
priest = Class(name="Priest", party_role="Heal or DPS", resources="Health, Mana, Insanity ", armor_type="Cloth", weapon="Daggers, One-handed Maces, Wands, Staves")
dk = Class(name="Death Knight", party_role="DPS or Tank", resources="Health, Runic power, Runes", armor_type="Plate", weapon="Axes, Maces, Swords, Polearms")
mage = Class(name="Mage", party_role="DPS", resources="Health and Mana", armor_type="Cloth", weapon="Wands, Daggers, One-handed Swords, Staves")
warrior = Class(name="Warrior", party_role="DPS or Tank", resources="Health and Rage", armor_type="Plate", weapon="Daggers, Fist Weapons, Axes, Swords, Maces, Polearms, Shields, Staves")
druid = Class(name="Druid", party_role="Tank, Heal, DPS", resources="Health, Mana, Rage, Energy, Astral power", armor_type="Leather", weapon="Daggers, Fist Weapons, Maces, Polearms, Staves")
paladin = Class(name="Paladin", party_role="Tank, Heal, DPS", resources="Health, Mana, Holy power", armor_type="Plate", weapon="Axes, Maces, Swords, Shields, Polearms")
hunter = Class(name="Hunter", party_role="DPS", resources="Health and Focus", armor_type="Mail", weapon="Axes, Bows, Crossbows, Daggers, Fist Weapons, Guns, Swords, Polearms, Staves")

orc = Race(name="Orc", available="Warrior, Hunter, Mage, Rogue, Warlock, Shaman, Monk, Death Knight", faction="Horde")
undead = Race(name="Undead", available="Warrior, Hunter, Mage, Rogue, Priest, Warlock, Monk, Death Knight", faction="Horde") 
tauren = Race(name="Tauren", available="Warrior, Hunter, Priest, Paladin, Druid, Shaman, Monk, Death Knight", faction="Horde")
troll = Race(name="Troll", available="Warrior, Hunter, Mage, Rogue, Priest, Warlock, Druid, Shaman, Monk, Death Knight", faction="Horde")
blood_elf = Race(name="Blood Elf", available="Warrior, Hunter, Mage, Rogue, Priest, Warlock, Paladin, Monk, Demon Hunter, Death Knight", faction="Horde")
goblin = Race(name="Goblin", available="Warrior, Hunter, Mage, Rogue, Priest, Warlock, Shaman, Death Knight", faction="Horde")
nightborne = Race(name="Nightborne", available="Warrior, Hunter, Mage, Rogue, Priest, Warlock, Monk, Death Knight", faction="Horde")
highmountain_tauren = Race(name="Highmountain Tauren", available="Warrior, Hunter, Druid, Shaman, Monk, Death Knight", faction="Horde")
maghar_orc = Race(name="Mag'har Orc", available="Warrior, Hunter, Mage, Rogue, Priest, Shaman, Monk, Death Knight", faction="Horde")
zandalari_troll = Race(name="Zandalari Troll", available="Warrior, Hunter, Mage, Rogue, Priest, Paladin, Druid, Shaman, Monk, Death Knight", faction="Horde")
vulpera = Race(name="Vulpera", available="Warrior, Hunter, Mage, Rogue, Priest, Warlock, Shaman, Monk, Death Knight", faction="Horde")
pandaren = Race(name="Pandaren", available="Warrior, Hunter, Mage, Rogue, Priest, Shaman, Monk, Death Knight", faction="Horde or Alliance")
human = Race(name="Human", available="Warrior, Hunter, Mage, Rogue, Priest, Warlock, Paladin, Monk, Death Knight", faction="Alliance")
dwarf = Race(name="Dwarf", available="Warrior, Hunter, Mage, Rogue, Priest, Warlock, Paladin, Shaman, Monk, Death Knight", faction="Alliance")
night_elf = Race(name="Night Elf", available="Warrior, Hunter, Mage, Rogue, Priest, Druid, Monk, Demon Hunter, Death Knight", faction="Alliance")
gnome = Race(name="Gnome", available="Warrior, Hunter, Mage, Rogue, Priest, Warlock, Monk, Death Knight", faction="Alliance")
draenei = Race(name="Draenei", available="Warrior, Hunter, Mage, Priest, Paladin, Shaman, Monk, Death Knight", faction="Alliance")
worgen = Race(name="Worgen", available="Warrior, Hunter, Mage, Rogue, Priest, Warlock, Druid, Death Knight", faction="Alliance")
void_elf = Race(name="Void Elf", available="Warrior, Hunter, Mage, Rogue, Priest, Warlock, Monk, Death Knight", faction="Alliance")
lightforged_draenei = Race(name="Lightforged Draenei", available="Warrior, Hunter, Mage, Priest, Paladin, Death Knight", faction="Alliance")
dark_iron_dwarf = Race(name="Dark Iron Dwarf", available="Warrior, Hunter, Mage, Rogue, Priest, Warlock, Paladin, Shaman, Monk, Death Knight", faction="Alliance")
kul_tiran = Race(name="Kul Tiran", available="Warrior, Hunter, Mage, Rogue, Priest, Druid, Shaman, Monk, Death Knight", faction="Alliance")
mechagnome = Race(name="Mechagnome", available="Warrior, Hunter, Mage, Rogue, Priest, Warlock, Monk, Death Knight", faction="Alliance")

alchemy = Profession(name="Alchemy")
blacksmithing = Profession(name="Blacksmithing")
engineering = Profession(name="Engineering")
leatherworking = Profession(name="Leatherworking")
tailoring = Profession(name="Tailoring")
herbalism = Profession(name="Herbalism")
mining = Profession(name="Mining")
skinning = Profession(name="Skinning")
enchanting = Profession(name="Enchanting")
inscription = Profession(name="Inscription")
jewelcrafting = Profession(name="Jewelcrafting")
cooking = Profession(name="Cooking")
fishing = Profession(name="Fishing")
archaeology = Profession(name="Archaeology")
first_aid = Profession(name="First Aid")

yamiyosei = Game(username="Yamiyosei", level="60lv", class_=dh, race=blood_elf, profession=alchemy)

session.add_all([dh, monk, shaman, warlock, rogue, priest, dk, mage, warrior, druid, paladin, hunter])
session.add_all([orc, undead, tauren, troll, blood_elf, goblin, nightborne,
highmountain_tauren, maghar_orc, zandalari_troll, vulpera, pandaren, 
human, dwarf, night_elf, gnome, draenei, worgen, void_elf, lightforged_draenei, 
dark_iron_dwarf, kul_tiran, mechagnome])
session.add_all([alchemy, blacksmithing, engineering, leatherworking, tailoring,
herbalism, mining, skinning, enchanting, inscription, jewelcrafting, cooking, fishing, archaeology, first_aid])
session.add(yamiyosei)
session.commit()
